### ISSUE TITLE
[BUG] tests "OperatorTests.cu" and "ReductionTests.cu" fail to compile

### ISSUE THREAD

**Issue by siegLoesch** [NVIDIA/MatX#415] opened 2023-05-10 10:45 UTC
Being aware that you were working hard to improve the correct compilation of unit tests I upgraded MatX to revision: _20230506.134328_. Nearly all of the unit tests comiple without failure but not  "_OperatorTests.cu_" and "_ReductionTests.cu_" [_see: 
[MatXConfBuildInstallFailedTests.log](https://github.com/NVIDIA/MatX/files/11440856/MatXConfBuildInstallFailedTests.log)_
]. For the moment I excluded those two from the list <_test_sources_> given in the file <_$MATX_HOME/test/CMakeLists.txt_>.
The same, with the same files, happens as soon as activate the cmake benchmarks option with _-DMATX_BUILD_BENCHMARKS:BOOL=YES_ which I deactivated at the moment because I do not know if they are neccessary to run the bench.

Please find system and cuda versions inside the above attached file and let me know if I doing something wrong or wheter you are already aware of this.

Best regards
Siegfried

**Comment by siegLoesch** [comment] 2023-05-11 10:06
Hello Cliff,
thank you for your fast response!
I had your note in mind but thought you solved these issues already. The reason is that I tried to use CUDA 11.8 before with much less success. The reason for that might be that my default host compiler is gcc-12.2 which is not compatible with 11.8 what requires <-allow-unsupported-compiler> to be used [see: 
_[MatXConfBuildInstallFailedTests-gcc-12_2-Cuda-11_8.log](https://github.com/NVIDIA/MatX/files/11450807/MatXConfBuildInstallFailedTests-gcc-12_2-Cuda-11_8.log)_].
But using a combination of gcc-11.3 with CUDA 11.8 [see: 
_[MatXConfBuildInstallFailedTests-gcc-11_3-Cuda-11_8.log](https://github.com/NVIDIA/MatX/files/11450813/MatXConfBuildInstallFailedTests-gcc-11_3-Cuda-11_8.log)_
] also results in much more compile errors for the tests as using gcc-12.2 / CUDA 12.1 (here only 2 of all tests fail).
I know that Debian Bookworm is still not stable but should be soon (nearly stable).
MatX will be a great tool for my numerical computations and I will wait for your further progress and have to thank you all for your efforts!

Best regards
Siegfried

**Comment by cliffburdick** [comment] 2023-05-11 17:30
Hi @siegLoesch, unfortunately the compiler problem is not something we (MatX) can fix, but it's being addressed by the compiler team already for an upcoming cuda release. You are correct that gcc 12 is not officially supported by CUDA 11.8, but gcc 11 should be I believe. Are you sure something isn't wrong with the install in your gcc log? It appears that even though your compiler is gcc 11.3, it's still looking for libstdc++ in /usr/include/c++/12, when I think it should be in /11/. 

Can you ensure that the compiler in the case of 11.3 is installed correctly?

**Comment by cliffburdick** [comment] 2023-05-17 15:53
Thanks @siegLoesch, I will try to take a look at this today if I get time.

**Comment by cliffburdick** [comment] 2023-05-18 02:56
Hi @siegLoesch, can you please open iterator.h in and change line 114 to: 

```
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
      offset_++;
  #pragma GCC diagnostic pop
```
that will disable the warning. I don't know why it's happening yet since I need to reproduce it here, but that might get you a little further.

**Comment by cliffburdick** [comment] 2023-05-22 17:34
`Remark 2`: Thanks! I will update our minimum version. 

`Remark 3`: CPM is what we use internally for package management, so it will be using that if you build the tests. It looks like that test is failing to release the tensor properly after it goes out of scope. For now you can safely ignore those tests since you likely aren't using DLPack unless you're interfacing with Python. We will look into those and see if we can reproduce them.

**Comment by cliffburdick** [comment] 2023-05-23 19:18
Hi @siegLoesch I incorporated your CMake change for the files going to the binary directory here: https://github.com/NVIDIA/MatX/pull/419/commits/adad5b3b9cb0dde16f0239eac30a770222676747

I modified the cupy check to make it more generalizable and disable the test rather than not compiling it so it will be more granular. We still have not reproduced your DLPack issue. If we can't reproduce it soon I'll request more info from you.

**Comment by siegLoesch** [comment] 2023-06-01 17:22
Nice solution - thanks a lot!
Compiled and ran the unit tests with and without __cupy__ on bullseye which yields the same result: only the __dlpack__ tests fail.

Regards
Siegfried

**Comment by cliffburdick** [comment] 2023-06-01 22:26
Hi @siegLoesch, I found a real fix for the iterator error and will push it shortly. Still looking into the dlpack bug.

**Comment by cliffburdick** [comment] 2023-06-01 23:46
Hi @siegLoesch, all issues have been reproduced and fixed. Please give `main` a try and let us know if you have more issues.

**Closed by cliffburdick** 2023-06-01 23:46 UTC

**Comment by siegLoesch** [comment] 2023-06-04 17:11
Works like a charme, here is the result of my build script:
_matx_test successfully passed all tests!_ .
Pretty good job - thank you!
I will proceed with your notebooks now and let you know!
Best regards
Siegfried
